### ISSUE TITLE
Question on schematic

### ISSUE THREAD

**Issue by aluedt** [jbeuckm/808-Hihats#1]
Hi, thanks for this lovely project. I've got a small question on the schematic. The decay potentiometer is labelled with "2MB", what does this mean? What kind of potentiometer is this actually? 100K .. 10K?

Thanks in advance
--Andree
![808hh_question](https://user-images.githubusercontent.com/32669364/52915542-b5bd0f80-32d5-11e9-9abf-66994d3be629.png)

**Comment by jbeuckm** [comment]
Hi Andree,

It's a good idea to double check with the 808 service manual
<http://privat.bahnhof.se/wb447909/dinsync/service_manuals/TR-808.pdf>.
This one is 2Megohms. The "B" means linear curve:
http://www.resistorguide.com/potentiometer-taper/

**Comment by aluedt** [comment]
Thank's a lot!
